[package]
name = "rendust"
version = "0.1.0"
authors = ["quadrifoglio <quadrifoglio.clement@protonmail.com>"]

[dependencies]
gl = "*"
libc = "*"
glutin = "0.9.2"
cgmath = "0.14.1"
lazy_static = "0.2"

[dev-dependencies]
imagefmt = "4.0.0"
